version: '3.8'

services:
  # Servicio para el API Gateway
  api-gateway:
    image: hormonal-care-api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"  # Mapea el puerto 8000 del contenedor al 8000 de la VM
    environment:
      - DB_HOST=junction.proxy.rlwy.net 
      - DB_PORT=18827
      - DB_USER=root
      - DB_PASSWORD=tptIIdsajhIcJGRTCGsPaEwWMtfTUvxN
    networks:
      - app-network
    restart: unless-stopped

  # Servicio para el microservicio communication
  communication:
    image: hormonal-care-microservice-communication
    container_name: communication
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=junction.proxy.rlwy.net
      - DB_PORT=18827
      - DB_USER=root
      - DB_PASSWORD=tptIIdsajhIcJGRTCGsPaEwWMtfTUvxN
    networks:
      - app-network
    restart: unless-stopped

  # Servicio para el microservicio IAM
  iam:
    image: hormonal-care-microservice-iam
    container_name: iam
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=junction.proxy.rlwy.net
      - DB_PORT=18827
      - DB_USER=root
      - DB_PASSWORD=tptIIdsajhIcJGRTCGsPaEwWMtfTUvxN
    networks:
      - app-network
    restart: unless-stopped

  # Servicio para el microservicio medicalRecord
  medicalRecord:
    image: hormonal-care-microservice-medicalRecord
    container_name: medicalRecord
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=junction.proxy.rlwy.net
      - DB_PORT=18827
      - DB_USER=root
      - DB_PASSWORD=tptIIdsajhIcJGRTCGsPaEwWMtfTUvxN
    networks:
      - app-network
    restart: unless-stopped

  # Servicio para el microservicio notifications
  notifications:
    image: hormonal-care-microservice-notifications
    container_name: notifications
    ports:
      - "8084:8084"
    environment:
      - DB_HOST=junction.proxy.rlwy.net
      - DB_PORT=18827
      - DB_USER=root
      - DB_PASSWORD=tptIIdsajhIcJGRTCGsPaEwWMtfTUvxN
    networks:
      - app-network
    restart: unless-stopped

# Definición de la red personalizada
networks:
  app-network:
    driver: bridge
