# Configuración para Docker - Communication Microservice
spring.application.name=hormonal-care-communication

# Configuración MongoDB para Docker
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://mongodb:27017/hormonal_care_communication}

# Puerto del microservicio
server.port=8084

# OpenAPI Configuration
springdoc.api-docs.path=/communication/v3/api-docs
springdoc.swagger-ui.path=/communication/swagger-ui.html
