# Configuración para Docker - Notification Microservice
spring.application.name=hormonalcare-notification

# Configuración de base de datos para Docker
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-db:3306/hormonal_care?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Puerto del microservicio
server.port=8083

# Configuración JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=com.backend.hormonalcare.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCase
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# OpenAPI Configuration
springdoc.api-docs.path=/notification/v3/api-docs
springdoc.swagger-ui.path=/notification/swagger-ui.html
